further account.cpp refactoring
Gnucash/gnucash pull request #1105
Opened 2021-08-06 13:50 UTC by christopherlam

Continuation of #1101 

The GList* returned by `gnc_account_lookup_by_type_and_commodity` may not be in the same order.

2021-08-07 21:42 UTC, jralls commented
You know, pushing more changes suggests that it wasn't in fact ready for review.

2021-08-07 22:18 UTC, jralls requested changes

2021-08-07 22:18 UTC, jralls commented on libgnucash/engine/Account.cpp
> +    account_foreach_descendant (account, process_acct_depth, &depth, FALSE);
Also a pessimisation: Create that list of 3125 accounts and then traverse the parents backwards to the top counting the steps, compared to counting down once for each account.

2021-08-07 22:18 UTC, jralls commented on libgnucash/engine/Account.cpp
> +            fullname = name + sep + fullname;
Another pessimization: Allocations are expensive and you've got three for every step.

2021-08-09 04:40 UTC, christopherlam commented
let's close it. more difficult than expected... shorter != fast

2021-08-09 04:40 UTC, closed without merging

2021-08-09 04:43 UTC, jralls commented
> shorter != fast

A valuable lesson. ;-)