Maint leaks
Gnucash/gnucash pull request #1113
Opened 2021-08-19 14:31 UTC by christopherlam

More valgrind leaks... continuation of #1107 

because `gtk_container_get_children` always returns a new GList* and they were not consistently freed after use.

2021-08-19 17:45 UTC, jralls requested changes

2021-08-19 17:45 UTC, jralls commented on gnucash/gnome-utils/gnc-amount-edit.c
> +            g_free (filtered_string);
You don't need a null check, `g_free` does one.

2021-08-19 17:45 UTC, jralls commented on gnucash/gnome-search/dialog-search.c
>              GtkWidget *combo_box = children->data;
```
GList *children = gtk_container_get_children (GTK_CONTAINER(data->container));

for (GList *child = children; child; child = g_list_next(child))
    GtkWidget *combo_box = child->data;
```

2021-08-19 17:45 UTC, jralls commented on gnucash/gnome-utils/dialog-options.c
>          g_list_free (list);
Free the list first so `g_return_val_if_fail` doesn't leak it.

2021-08-19 17:45 UTC, jralls commented on gnucash/gnome-utils/gnc-main-window.c
> +    for (children = allchildren; children; children = children->next)
Same as above: `child` and `children` not `children` and `allchildren`.

2021-08-20 01:25 UTC, merged

2021-08-20 02:09 UTC, christopherlam commented on bindings/engine.i
> +%typemap(freearg) GSList * "g_slist_free_full ($1, g_free);"
oops I think this should be `%typemap(freearg) GSList *key_path "g_slist_free_full ($1, g_free);"` to avoid poisoning other GSList* args