Minor options fixes
Gnucash/gnucash pull request #1557
Opened 2023-03-07 11:49 UTC by richardcohen

2023-03-16 22:55 UTC, jralls requested changes

2023-03-17 15:55 UTC, richardcohen commented on libgnucash/engine/gnc-option-impl.cpp
> -
Did you try it? It certainly does work.
Pointer comparison is fine for the const char*.
GncItem.second is GncGUID, which gcc can convert to GUID for operator!=
Xcode won't do that conversion, so needs to use operator==(const GncGUID&, const GncGUID&)

2023-03-17 15:55 UTC, richardcohen commented on libgnucash/engine/gnc-option-impl.cpp
> +
See above - to get Xcode to compile.

2023-03-17 15:58 UTC, richardcohen commented on libgnucash/engine/gnc-optiondb.cpp
> +                                   }), m_options.end());
It's better to use the standard version of the idiom, to avoid surprising static analysers and other programmers.

2023-03-18 20:55 UTC, merged

2023-03-18 20:57 UTC, jralls commented on libgnucash/engine/gnc-option-impl.cpp
> -
Interestingly it's because clang refuses to look inside `namespace gnc`, even if told `using namespace gnc;` for the constructor.

2023-03-18 20:58 UTC, jralls commented
Thanks.