Bug 799305 - Crash when there is more than one unknown quote source for commodities
Gnucash/gnucash pull request #1936
Opened 2024-05-09 06:44 UTC by christopherlam

instead of vector which requires reallocation, use a c++ linked list.

2024-05-09 16:11 UTC, jralls requested changes
The first commit duplicates #1900, but something's fishy about it: CMakeLists.txt [specifies C++ 17](https://github.com/Gnucash/gnucash/blob/f3b203f4dbd4e9bb02ebecf8b9beaf19b57cbd76/CMakeLists.txt#L599), not C++ 20. Is that not making it into the flags passed to the compiler or has a recent release of GCC decided that C++20 compiance is required regardless of what's passed as `-std=`?

2024-05-09 16:11 UTC, jralls commented on libgnucash/engine/test/test-commodities.cpp
> +    auto first =gnc_quote_source_lookup_by_ti (SOURCE_UNKNOWN, 0);
whitespace error.

2024-05-09 16:11 UTC, jralls commented on libgnucash/engine/test/test-commodities.cpp
> +    for (auto i = 0; i < 10000; ++i)
You don't need anywhere near that many iterations. Somewhere in the 10-20 range should be sufficient; it will depend a bit on the c++ library implementation.

2024-05-10 00:07 UTC, merged

2024-05-10 00:25 UTC, christopherlam commented
> The first commit duplicates #1900, but something's fishy about it: CMakeLists.txt [specifies C++ 17](https://github.com/Gnucash/gnucash/blob/f3b203f4dbd4e9bb02ebecf8b9beaf19b57cbd76/CMakeLists.txt#L599), not C++ 20. Is that not making it into the flags passed to the compiler or has a recent release of GCC decided that C++20 compiance is required regardless of what's passed as `-std=`?

Dunno latest ci is failing on arch only

2024-05-10 00:45 UTC, jralls commented
It's a GCC bug. The [documentation](https://gcc.gnu.org/onlinedocs/gcc-14.1.0/gcc/C_002b_002b-Dialect-Options.html) says "-Wtemplate-id-cdtor is enabled by default with -std=c++20; it is also enabled by -Wc++20-compat", the args passed to the compiler say `-std=c++17`.

I don't have a gcc bugzilla account and you have to request one by email so I'm not going to file one. I've merged #1900 so the problem goes away.