Bug799047 - AutoComplete Only Considers Visible Transaction
Gnucash/gnucash pull request #1961
Opened 2024-06-17 14:21 UTC by Bob-IT

In the past, all transactions were used on the first load of the register and this is when the autocomplete would be populated, on
subsequent loads it would be a filtered list. With the change to delay loading the register, the first load split list is empty and the autocomplete is now being populated by the filtered list.

To fix this, make a copy of the original query and compare this query to the query used for refresh. When different, pass a second full list of splits to the register to populate the autocomplete lists.

2024-06-26 14:17 UTC, jralls requested changes

2024-06-26 14:17 UTC, jralls commented on gnucash/register/ledger-core/gnc-ledger-display.c
> +    start = start - 2592000; // the default is to show last 30 days
Let's not have the magic number:
```C
static const time64 secs_per_thirty_days = 2592000;
start = gnc_time64_get_today_start () - secs_per_thirty_days;
```

2024-06-26 14:17 UTC, jralls commented on gnucash/register/ledger-core/split-register-load.c
> +                 Split* split, gboolean has_last_num)
Why the name change? It's adding completions to quick fill cells.

2024-06-27 09:06 UTC, Bob-IT commented on gnucash/register/ledger-core/gnc-ledger-display.c
> +    start = start - 2592000; // the default is to show last 30 days
Changed, thank you.

2024-06-27 09:08 UTC, Bob-IT commented on gnucash/register/ledger-core/split-register-load.c
> +                 Split* split, gboolean has_last_num)
I think I changed the name when I was going to use it for all completions but decided to do it as this PR but forgot to change it back, done.

2024-06-27 17:36 UTC, merged

2024-06-27 17:42 UTC, jralls commented
Thanks.