Use ICU date interval formatter
Gnucash/gnucash pull request #2018
Opened 2024-09-14 14:29 UTC by christopherlam

when everything looks like a nail with icu... use ICU's date interval formatter:

ja_JP
![image](https://github.com/user-attachments/assets/4f971551-a4f6-4526-91b5-7741b241478e)

de_DE -- it omits month if unchanged
![image](https://github.com/user-attachments/assets/958a078f-473b-4ac1-b336-4d0673a8a040)

2026-02-12 00:50 UTC, jralls commented
`gnc_date_interval_format` should be in gnc-date.h/cpp right next to `qof_print_date`.

2026-02-12 11:31 UTC, christopherlam commented
Here's a funny one: in `date_interval_format` the `interval` is a `new icu::DateInterval` object. There's no `delete`. If I add a `delete` it segfaults with double free. The documentation at https://unicode-org.github.io/icu-docs/apidoc/dev/icu4c/classicu_1_1DateIntervalFormat.html also doesn't have `delete`.

EDIT: changed `format` signature to include `FieldPosition` which is more tolerant of the `interval`...

2026-02-12 17:12 UTC, jralls commented
> Here's a funny one: in date_interval_format the interval is a new icu::DateInterval object. There's no delete. If I add a delete it segfaults with double free. The documentation at https://unicode-org.github.io/icu-docs/apidoc/dev/icu4c/classicu_1_1DateIntervalFormat.html also doesn't have delete.

Huh? You don't need to delete it manually because you've wrapped it in a `unique_ptr`. The example code in DateIntervalFormat.html doesn't do that and does delete it manually. Using a `unique_ptr` is better.

2026-02-12 22:20 UTC, christopherlam commented
> > Here's a funny one: in date_interval_format the interval is a new icu::DateInterval object. There's no delete. If I add a delete it segfaults with double free. The documentation at https://unicode-org.github.io/icu-docs/apidoc/dev/icu4c/classicu_1_1DateIntervalFormat.html also doesn't have delete.
> 
> Huh? You don't need to delete it manually because you've wrapped it in a `unique_ptr`. The example code in DateIntervalFormat.html doesn't do that and does delete it manually. Using a `unique_ptr` is better.

Ok but I'm referring to the interval object, not the interval formatter object...

Here's a previous iteration:

```cpp
icu_date_interval_format (time64 from_date, time64 to_date)
{
    auto difmt = get_icu_date_interval_formatter();
    if (!difmt)
    {
        PWARN("DateIntervalFormat initialization failed");
        return nullptr;
    }

    if (from_date > to_date)
        std::swap(from_date, to_date);

    auto interval = new icu::DateInterval (from_date * 1000, to_date * 1000);

    icu::UnicodeString result;
    UErrorCode status = U_ZERO_ERROR;
    difmt->format(interval, result, status);
    if (U_FAILURE(status))
    {
        PWARN("Error formatting interval");
        return nullptr;
    }

    std::string interval_string;
    result.toUTF8String(interval_string);
//    delete interval;

    return g_strdup (interval_string.c_str());
}
```

Note the `delete interval` will cause double free.

2026-02-13 05:27 UTC, jralls commented
Hmm. Must be more to it, I tried to reproduce by putting back the allocated DateInterval and couldn't get it to crash. I also tried an Asan build and it doesn't complain either.

Anyway, there's no good reason to allocate the DateInterval so it's moot.

2026-02-13 05:39 UTC, jralls requested changes
A few nits, otherwise fine.

2026-02-13 05:39 UTC, jralls commented on gnucash/report/trep-engine.scm
> +                              (+ beginweekt64 (* 9 86400)))))
Name the magic number:
```
(let* ((secs-per-day 86400)
       (beginweekt64 (* (gnc:time64-get-week (gnc-mktime date)) 7 secs-per-day)))
```
etc.

2026-02-13 05:39 UTC, jralls commented on libgnucash/engine/gnc-date.cpp
> +        if (U_FAILURE(status))
Maybe do a PWARN here with the error code?

2026-02-13 05:39 UTC, jralls commented on libgnucash/engine/gnc-date.cpp
> +        PWARN("DateIntervalFormat initialization failed");
Instead of this one which doesn't tell us why it failed.

2026-02-13 05:39 UTC, jralls commented on libgnucash/engine/gnc-date.cpp
> +        PWARN("Error formatting interval");
`PWARN("Error formatting interval: %d", status);`

2026-02-13 16:56 UTC, jralls approved these changes

2026-02-13 23:09 UTC, merged

2026-02-13 23:52 UTC, christopherlam commented
Ok

Here's the backtrace with the old `format` without `FieldPosition`. I have ICU 73.1.

```cpp
modified   libgnucash/engine/gnc-date.cpp
@@ -645,9 +645,8 @@ icu_date_interval_format (time64 from_date, time64 to_date)
 
     icu::DateInterval interval (from_date * 1000.0, to_date * 1000.0);
     icu::UnicodeString result;
-    icu::FieldPosition fp;
     UErrorCode status = U_ZERO_ERROR;
-    difmt->format (&interval, result, fp, status);
+    difmt->format (&interval, result, status);
     if (U_FAILURE(status))
     {
         PWARN("Error formatting interval: %d", status);
```

backtrace:
```
(gdb) bt
#0  0x00007ffff55c4773 in free () from /gnu/store/yj053cys0724p7vs9kir808x7fivz17m-glibc-2.41/lib/libc.so.6
#1  0x00007ffff6138b5e in icu_73::UMemory::operator delete(void*) () from /gnu/store/dp22sbnf9z87ikibqxwhjnm092xh8yhm-profile/lib/libicuuc.so.73
#2  0x00007ffff5d91abf in icu_73::Formattable::dispose() () from /gnu/store/dp22sbnf9z87ikibqxwhjnm092xh8yhm-profile/lib/libicui18n.so.73
#3  0x00007ffff5d91b37 in icu_73::Formattable::~Formattable() () from /gnu/store/dp22sbnf9z87ikibqxwhjnm092xh8yhm-profile/lib/libicui18n.so.73
#4  0x00007ffff65c4852 in icu_date_interval_format (from_date=<optimized out>, to_date=<optimized out>) at /home/chris/sources/gnucash/stable/libgnucash/engine/gnc-date.cpp:649
#5  gnc_date_interval_format (from_date=1766880000, to_date=1767398400) at /home/chris/sources/gnucash/stable/libgnucash/engine/gnc-date.cpp:668
#6  0x00007ffff6aa8444 in _wrap_gnc_date_interval_format (s_0=<optimized out>, s_1=0x1a5617002) at /home/chris/sources/gnucash/build-stable/bindings/guile/swig-engine.cpp:22873
#7  0x00007ffff7df5340 in ?? () from /gnu/store/zkq8h96kjpgv0lkmwdn5s5lrnrryp0pv-guile-3.0.9/lib/libguile-3.0.so.1
#8  0x00007ffff7e03045 in scm_call_n () from /gnu/store/zkq8h96kjpgv0lkmwdn5s5lrnrryp0pv-guile-3.0.9/lib/libguile-3.0.so.1
#9  0x00007ffff7d6d308 in scm_call_1 () from /gnu/store/zkq8h96kjpgv0lkmwdn5s5lrnrryp0pv-guile-3.0.9/lib/libguile-3.0.so.1
#10 0x00007ffff7b2fca8 in gnc_run_report_with_error_handling (report_id=<optimized out>, data=data@entry=0x7fffffffb598, errmsg=errmsg@entry=0x7fffffffb528)
    at /home/chris/sources/gnucash/stable/gnucash/report/gnc-report.cpp:222
#11 0x00007ffff7b3034e in gnc_run_report_id_string_with_error_handling (id_string=id_string@entry=0xa33370 "id=0", data=data@entry=0x7fffffffb598, errmsg=errmsg@entry=0x7fffffffb528)
    at /home/chris/sources/gnucash/stable/gnucash/report/gnc-report.cpp:298
#12 0x00007ffff7c1fdd7 in gnc_report_system_report_stream_cb (location=location@entry=0xa33370 "id=0", data=data@entry=0x7fffffffb598, len=len@entry=0x7fffffffb594)
    at /home/chris/sources/gnucash/stable/gnucash/gnome/gnc-plugin-report-system.c:155
#13 0x00007ffff7ac314c in load_to_stream (self=self@entry=0x1b7b720, type=0x1bf9410 "report", location=location@entry=0xa33370 "id=0", label=label@entry=0x0)
    at /home/chris/sources/gnucash/stable/gnucash/html/gnc-html-webkit2.c:490
#14 0x00007ffff7ac38fb in impl_webkit_show_url (self=0x1b7b720, type=<optimized out>, location=<optimized out>, label=<optimized out>, new_window_hint=<optimized out>)
    at /home/chris/sources/gnucash/stable/gnucash/html/gnc-html-webkit2.c:890
#15 0x00007ffff7ac03d3 in gnc_html_show_url (self=0x1b7b720, type=<optimized out>, location=0xa33370 "id=0", label=0x0, new_window_hint=0) at /home/chris/sources/gnucash/stable/gnucash/html/gnc-html.c:369
#16 0x00007ffff7c3af93 in gnc_plugin_page_report_load_uri (page=0x1b43ef0) at /home/chris/sources/gnucash/stable/gnucash/gnome/gnc-plugin-page-report.cpp:449
#17 gnc_plugin_page_report_focus_widget (report_plugin_page=0x1b43ef0) at /home/chris/sources/gnucash/stable/gnucash/gnome/gnc-plugin-page-report.cpp:336
#18 gnc_plugin_page_report_focus_widget (report_plugin_page=0x1b43ef0) at /home/chris/sources/gnucash/stable/gnucash/gnome/gnc-plugin-page-report.cpp:302
#19 0x00007ffff6309382 in ?? () from /gnu/store/dp22sbnf9z87ikibqxwhjnm092xh8yhm-profile/lib/libglib-2.0.so.0
#20 0x00007ffff630c517 in ?? () from /gnu/store/dp22sbnf9z87ikibqxwhjnm092xh8yhm-profile/lib/libglib-2.0.so.0
#21 0x00007ffff630ceef in g_main_loop_run () from /gnu/store/dp22sbnf9z87ikibqxwhjnm092xh8yhm-profile/lib/libglib-2.0.so.0
#22 0x00007ffff74043f5 in gtk_main () from /gnu/store/dp22sbnf9z87ikibqxwhjnm092xh8yhm-profile/lib/libgtk-3.so.0
#23 0x00007ffff7a2f93e in gnc_ui_start_event_loop () at /home/chris/sources/gnucash/stable/gnucash/gnome-utils/gnc-gnome-utils.c:586
#24 0x000000000040fb70 in scm_run_gnucash (data=0x7fffffffc0d0, argc=<optimized out>, argv=<optimized out>) at /home/chris/sources/gnucash/stable/gnucash/gnucash.cpp:216
#25 0x00007ffff7d846bc in ?? () from /gnu/store/zkq8h96kjpgv0lkmwdn5s5lrnrryp0pv-guile-3.0.9/lib/libguile-3.0.so.1
#26 0x00007ffff7d6bc3a in ?? () from /gnu/store/zkq8h96kjpgv0lkmwdn5s5lrnrryp0pv-guile-3.0.9/lib/libguile-3.0.so.1
#27 0x00007ffff7df5340 in ?? () from /gnu/store/zkq8h96kjpgv0lkmwdn5s5lrnrryp0pv-guile-3.0.9/lib/libguile-3.0.so.1
#28 0x00007ffff7e03045 in scm_call_n () from /gnu/store/zkq8h96kjpgv0lkmwdn5s5lrnrryp0pv-guile-3.0.9/lib/libguile-3.0.so.1
#29 0x00007ffff7d6d32a in scm_call_2 () from /gnu/store/zkq8h96kjpgv0lkmwdn5s5lrnrryp0pv-guile-3.0.9/lib/libguile-3.0.so.1
#30 0x00007ffff7e16cd4 in ?? () from /gnu/store/zkq8h96kjpgv0lkmwdn5s5lrnrryp0pv-guile-3.0.9/lib/libguile-3.0.so.1
#31 0x00007ffff7defdaf in scm_c_catch () from /gnu/store/zkq8h96kjpgv0lkmwdn5s5lrnrryp0pv-guile-3.0.9/lib/libguile-3.0.so.1
#32 0x00007ffff7d6e0b6 in scm_c_with_continuation_barrier () from /gnu/store/zkq8h96kjpgv0lkmwdn5s5lrnrryp0pv-guile-3.0.9/lib/libguile-3.0.so.1
#33 0x00007ffff7def00a in ?? () from /gnu/store/zkq8h96kjpgv0lkmwdn5s5lrnrryp0pv-guile-3.0.9/lib/libguile-3.0.so.1
#34 0x00007ffff7cce198 in GC_call_with_stack_base () from /gnu/store/y3m3cx1kjmyhakq5rakc0384pfdysdx5-libgc-8.2.8/lib/libgc.so.1
#35 0x00007ffff7de9f68 in scm_with_guile () from /gnu/store/zkq8h96kjpgv0lkmwdn5s5lrnrryp0pv-guile-3.0.9/lib/libguile-3.0.so.1
#36 0x00007ffff7d8d555 in scm_boot_guile () from /gnu/store/zkq8h96kjpgv0lkmwdn5s5lrnrryp0pv-guile-3.0.9/lib/libguile-3.0.so.1
#37 0x000000000040f34f in Gnucash::Gnucash::start (this=this@entry=0x7fffffffc280, argc=4, argv=0x7fffffffc608) at /home/chris/sources/gnucash/stable/gnucash/gnucash.cpp:280
#38 0x000000000040ed5b in main (argc=<optimized out>, argv=<optimized out>) at /home/chris/sources/gnucash/stable/gnucash/gnucash.cpp:305
(gdb) f 4
#4  0x00007ffff65c4852 in icu_date_interval_format (from_date=<optimized out>, to_date=<optimized out>) at /home/chris/sources/gnucash/stable/libgnucash/engine/gnc-date.cpp:649
649	    difmt->format (&interval, result, status);
```

2026-02-14 00:00 UTC, jralls commented
OK. What you really need is where the first free was. Valgrind and Asan will both do that. I think Asan is easier.

2026-02-14 05:37 UTC, christopherlam commented
I note from the back trace that interval is being cast to icu::Formattable instead of icu::DateInterval* -- could this be the clue? Still wouldnt explain the premature delete

2026-02-14 20:09 UTC, jralls commented
OK, I can reproduce that now. (It didn't help before that I'd picked the P&L report because it uses a date interval, but it doesn't use *this* date interval). Here's the ASAN report on the invalid free:
```
Address 0x00016fdfb930 is located in stack of thread T0 at offset 432 in frame
    #0 0x00010525c224 in gnc_date_interval_format gnc-date.cpp:664

  This frame has 10 object(s):
    [32, 256) 'locale.i.i' (line 624)
    [320, 324) 'status.i.i' (line 625)
    [336, 400) 'ref.tmp.i.i' (line 626)
    [432, 456) 'interval.i' (line 646) <== Memory access at offset 432 is inside this variable
    [496, 560) 'result.i' (line 647)
    [592, 596) 'status.i' (line 648)
    [608, 720) 'ref.tmp.i' (line 649)
    [752, 776) 'interval_string.i' (line 656)
    [816, 851) 'from_buff' (line 673)
    [896, 931) 'to_buff' (line 673)
```
This rather [dubious design element](https://github.com/unicode-org/icu/blob/5861e1fd52f1d7673eee38bc3c965aa18b336062/icu4c/source/i18n/unicode/fmtable.h#L54) explains the problem: "As of ICU 3.0, Formattable may also wrap a UObject pointer, which it owns."  Notice that the first argument of Format::format is a `const Formattable &`, so the compiler constructs a Formattable from the `UObject*` passed in to it and the Formattable takes ownership of it. In doing so it assumes that it was allocated with operator new.

DateIntervalFormatter implements [`format(const DateInterval&, UnicodeStr&, FieldPosition&, UErrorCode&)`](https://github.com/unicode-org/icu/blob/5861e1fd52f1d7673eee38bc3c965aa18b336062/icu4c/source/i18n/dtitvfmt.cpp#L288)  bypassing creating the `Formattable` and dodging the ownership transfer. 

No doubt the ICU folks think the implicit ownership transfer is a feature. I think it's a wee bit too clever and should at least be more emphatically documented.

How did you conclude that adding the `FieldPosition` would fix the problem?

2026-02-14 23:15 UTC, christopherlam commented
> 
> How did you conclude that adding the `FieldPosition` would fix the problem?

gdb was the key. I saw the unexpected `Formattable` in the backtrace, looked up the ICU docs, couldn't find a function signature with 3 arguments from the DateInterval page, tried the proper function with FieldPosition, and it didn't crash.