Python c++ QofSessionImpl (draft)
Gnucash/gnucash pull request #732
Opened 2020-06-02 21:12 UTC by c-holtermann

This is an attempt to wrap the c++ parts of gnucash, starting with QofSessionImpl. Please have a look at it. It's development in progress. But the example python file works. I'll add some unit test before finishing this PR and clean up the commits. 

The log file change as in PR #731 is included and will be removed (https://github.com/Gnucash/gnucash/commit/247b9c2f48fd44a5f92c991c703c248f2010394d).

2020-06-03 03:58 UTC, jralls commented
Did I really tell you to wrap QofSessionImpl?
I've read through the code. It's not at all clear to me what you're trying to do.
Suggestion: First, write up your problem and your plan to solve it in English in a post to `gnucash-devel`. It's important to work out the general design before you start coding. Next code to your plan and clean up everything into a single commit for every step in the plan. That doesn't mean that you can't have more commits like "fix typo" and "cleanup white space" *while you're working*, it means that you do those commits in a way that you can squash them into a commit per step so that when you present the work for review the reviewer can step through the commits see a logical progression to the work. The 17 commits in this PR don't tell a story, they just bounce around.
The PR description should either restate the problem and sketch out the design and the steps to accomplish it or link to the email discussion (and links should point at https://lists.gnucash.org/pipermail, *not* at a parasite service like nabble and gmane).

2020-06-03 04:52 UTC, c-holtermann commented
Hey John, thank you for the comments. The talk had been in 2018:
https://lists.gnucash.org/pipermail/gnucash-devel/2018-August/042393.html

Sorry for not presenting my stuff in an adequate manner. I'll work on that.

2020-06-14 01:27 UTC, jralls requested changes
There's no need to have separate C and C++ wrappers, you can simply make the whole thing gnucash-core.cpp. SWIG is smart enough to deal with both. You can look at the SWIG parts of [my c++options](https://github.com/jralls/gnucash/tree/c%2B%2Boptions/libgnucash/app-utils) branch, in particular [this commit](https://github.com/jralls/gnucash/commit/9fc3e848d0dbc7de64343fee17245e4c6fc52375), for an example.

I'm not convinced that automatically determining whether to set `-c++` based on the output file extension is a good idea; I am sure that basing it on the last characters of a variable name is not. But a simple wrapper function something like
```
macro (gnc_add_swig_c++_python_command _target _out_var _output _input _include_dirs)
    set(SWIG_ARGS "-c++" "-procdoc" "sw-gnc-option-doc" "-procdocformat" "plain")
    gnc_add_swig_python_command(_target _out_var _output _input _include_dirs)
    unset(SWIG_ARGS)
endmacro()
```
might be easier to understand.

2020-06-27 17:14 UTC, c-holtermann commented
> There's no need to have separate C and C++ wrappers, you can simply make the whole thing gnucash-core.cpp. SWIG is smart enough to deal with both. You can look at the SWIG parts of [my c++options](https://github.com/jralls/gnucash/tree/c%2B%2Boptions/libgnucash/app-utils) branch, in particular [this commit](https://github.com/jralls/gnucash/commit/9fc3e848d0dbc7de64343fee17245e4c6fc52375), for an example.

Thank you for you valuable feedback. I'm looking into putting the c++ part into the c stuff (or for testing the other way around). I'll need some time for that.

2026-08-06 18:22 UTC, jralls commented
Superseded by #2186

2026-08-06 18:22 UTC, closed without merging