Fix typos in libgnucash/
Gnucash/gnucash pull request #899
Opened 2021-02-05 19:54 UTC by luzpaz

Found via `codespell -q 3 -L ans,ba,parm,parms,numer`

2021-02-05 20:52 UTC, fellen requested changes
I found 2 wrong interpreted strings, but perhaps a native speaker should review the end 's'es.

2021-02-05 20:52 UTC, fellen commented on libgnucash/doc/finutil.html
> -[Uu](ser) Display User Defined Variables
wrong

2021-02-05 20:52 UTC, fellen commented on libgnucash/doc/finutil.html
> +<li>[Uu](set) Display User Defined Variables
too

2021-02-05 21:21 UTC, luzpaz commented on libgnucash/doc/finutil.html
> -[Uu](ser) Display User Defined Variables
Sorry about that. Will revert.

2021-03-02 00:33 UTC, fellen commented
Applied after reverting the two undesired changes.

Thank you!

2021-03-02 00:33 UTC, closed without merging