while add a new customer/vendor/employee, the address is not necessary.
Gnucash/gnucash pull request #971
Opened 2021-04-10 04:54 UTC by duguqiubailee

sometime I just want to add a customer/vendor/employee as quickly as I can, then complete other information.

but the address is needed, and can’t skip this step.

It will be more efficient if remove the address step.

2021-04-19 00:01 UTC, jralls requested changes
Seems harmless. @gjanssens I checked all of the uses of `gncAddressGetAddrX` and they're all NULL-protected.

2021-05-17 19:15 UTC, gjanssens commented on gnucash/gnome/dialog-employee.c
> +    //}
And while removing it, remove the now obsolete comment as well.

2021-05-17 19:15 UTC, gjanssens commented
I'm fine with not requiring address information.

2021-05-18 05:09 UTC, fellen commented
> I'm fine with not requiring address information.

Shouldn't then a check issuing a warning be added before printing an invoice, which is not payed instantly or in advance?

2021-05-18 14:54 UTC, jralls commented
> Shouldn't then a check issuing a warning be added before printing an invoice, which is not payed instantly or in advance?

Why? It will be immediately obvious once the invoice is printed. Besides, an address on the invoice is useful only with window envelopes.

2021-05-18 16:04 UTC, fellen commented
> Why? It will be immediately obvious once the invoice is printed. Besides, an address on the invoice is useful only with window envelopes.

Why printing, if it is not valid?
In DE an invoice including VAT needs the 10 elements of [UStG §14](https://www.gesetze-im-internet.de/ustg_1980/__14.html) (4):
1. complete name and address of both seller and buyer
2. …

2021-05-18 16:16 UTC, jralls commented
Just because it's not valid in Germany doesn't make it invalid everywhere. We're not writing GnuCash just for Germans and there's no reason to annoy everyone else because an invoice might not meet Germany's requirements.

2021-05-18 16:29 UTC, fellen commented
As said before, it is not only DE, it is EU law. See `Content of invoices` in https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32006L0112&from=EN#d1e6510-1-1

2021-05-18 16:43 UTC, jralls commented
OK, we're not writing GnuCash only for Europeans either.

2021-05-20 16:56 UTC, gjanssens commented
And to add to that, "the other accounting application I'm using" doesn't require addresses either, yet it's validated for the European market.

Another example where the address is not needed is for a generic customer to invoice to whenever a specific customer is not required (small over the counter sales for example).

2021-05-23 14:07 UTC, fellen commented
> And to add to that, "the other accounting application I'm using" doesn't require addresses either, yet it's validated for the European market.

The software provider is not responsible for our potential tax fraud. Although the government forced the producers of cash registers to make it harder.

> Another example where the address is not needed is for a generic customer to invoice to whenever a specific customer is not required (small over the counter sales for example).

Right, up to 250 € no complete invoice is required, but this simplified invoices have neither name nor address. I usually had a client 0 for it with name "Barverkauf" and a space as address.

2021-05-23 14:10 UTC, fellen commented
There is another issue with this PR:
We offer also import to add that data. There we have stricter rules.
The rules of both ways should be consistent.

2021-05-23 15:49 UTC, jralls commented
> The rules of both ways should be consistent.

Right.

@TianXing-Yi please also remove the if block at https://github.com/Gnucash/gnucash/blob/maint/gnucash/import-export/customer-import/dialog-customer-import.c#L251.

2021-05-23 17:10 UTC, fellen commented
> @TianXing-Yi please also remove the if block at https://github.com/Gnucash/gnucash/blob/maint/gnucash/import-export/customer-import/dialog-customer-import.c#L251.

… and I prefer a parallel PR for [gnucash-docs](https://github.com/Gnucash/gnucash-docs) updating the behaviour there in both components:

Help:
1. C/gnucash-help/busnss-ar-customers1.html#busnss-ar-custnew2, 
2. C/gnucash-help/busnss-ap-vendors1.html#busnss-ap-vendornew2, too?
3. (missing in C/gnucash-help/gui-bussiness.html), but perhaps other places

Guide:
1. https://github.com/Gnucash/gnucash-docs/blob/maint/guide/C/ch_import_business_data.xml
2. C/gnucash-guide/bus_ar.html#bus-ar-customers1 (IMHO this section is doubtful)
3. C/gnucash-guide/bus_ap.html#bus-ap-vendors1, too?
4. more?

2021-06-08 18:47 UTC, jralls commented
@TianXing-Yi Are you going to rework this as requested?

2021-06-10 17:50 UTC, TianXing-Yi commented
> @TianXing-Yi Are you going to rework this as requested?

Yeah Yeah, I will going to rework tomorrow, 

Thanks for all your help, thanks very much

2021-06-10 17:53 UTC, TianXing-Yi commented
> > @TianXing-Yi please also remove the if block at https://github.com/Gnucash/gnucash/blob/maint/gnucash/import-export/customer-import/dialog-customer-import.c#L251.
> 
> 
> 
> … and I prefer a parallel PR for [gnucash-docs](https://github.com/Gnucash/gnucash-docs) updating the behaviour there in both components:
> 
> 
> 
> Help:
> 
> 1. C/gnucash-help/busnss-ar-customers1.html#busnss-ar-custnew2, 
> 
> 2. C/gnucash-help/busnss-ap-vendors1.html#busnss-ap-vendornew2, too?
> 
> 3. (missing in C/gnucash-help/gui-bussiness.html), but perhaps other places
> 
> 
> 
> Guide:
> 
> 1. https://github.com/Gnucash/gnucash-docs/blob/maint/guide/C/ch_import_business_data.xml
> 
> 2. C/gnucash-guide/bus_ar.html#bus-ar-customers1 (IMHO this section is doubtful)
> 
> 3. C/gnucash-guide/bus_ap.html#bus-ap-vendors1, too?
> 
> 4. more?

Ok OK ，Get these, I will try to do it 

Thanks very much

2021-06-11 15:21 UTC, TianXing-Yi commented
@jralls @fellen 

Hi sir, by your suggestion, I have commented out the code below, and the project compiles normally.
Should I now pull a new request from vscode, or do anything else first ?

dialog.vendor.c
```
    /* Make sure we have an address */
    if (check_entry_nonempty (vw->addr1_entry, NULL) &&
            check_entry_nonempty (vw->addr2_entry, NULL) &&
            check_entry_nonempty (vw->addr3_entry, NULL) &&
            check_entry_nonempty (vw->addr4_entry, NULL))
    {
        const char *msg = _("You must enter a payment address.");
        gnc_error_dialog (gnc_ui_get_gtk_window (widget), "%s", msg);
        return;
    }
```

dialog.employee.c
```
    /* Check for valid username */
    if (check_entry_nonempty (ew->username_entry,
                              _("You must enter a username.")))
        return;

    /* Make sure we have an address */
    if (check_entry_nonempty (ew->addr1_entry, NULL) &&
            check_entry_nonempty (ew->addr2_entry, NULL) &&
            check_entry_nonempty (ew->addr3_entry, NULL) &&
            check_entry_nonempty (ew->addr4_entry, NULL))
    {
        const char *msg = _("You must enter an address.");
        gnc_error_dialog (gnc_ui_get_gtk_window (widget), "%s", msg);
        return;
    }
```

dialog.customer.c
```
    /* Make sure we have an address */
    if (check_entry_nonempty (cw->addr1_entry, NULL) &&
            check_entry_nonempty (cw->addr2_entry, NULL) &&
            check_entry_nonempty (cw->addr3_entry, NULL) &&
            check_entry_nonempty (cw->addr4_entry, NULL))
    {
        const char *msg = _("You must enter a billing address.");
        gnc_error_dialog (gnc_ui_get_gtk_window (widget), "%s", msg);
        return;
    }
```

dialog-customer-import.c
```
        // At least one of the address fields must have a value.
        // If not, then delete the row.
        if (strlen(addr1) == 0 && strlen(addr2) == 0 && strlen(addr3) == 0 && strlen(addr4) == 0)
        {
            valid = gtk_list_store_remove (store, &iter);
            (*deleted)++;
            continue;
        }
```

2021-06-11 15:56 UTC, jralls commented
> Hi sir, by your suggestion, I have commented out the code below, and the project compiles normally, report works well.

I didn't tell you to comment out anything. I told you to *remove* code *instead* of commenting it out. Perhaps that's what you did but didn't get the English quite right.

Whatever you do in your editor doesn't matter until you amend your commits and force-push them to github repo. Since you split the change into two commits it's probably simplest to reset back to before them and re-commit.  I don't use vscode so I can't tell you how to do that from inside it. From a unix command line (MSYS2 terminal window if you're using Windows):
```
   git reset HEAD^^
   git add gnucash/gnome/dialog-employee.c
   git commit -m "remove setting address while add a new employee"
   git add gnucash/gnome/dialog-vendor.c
   git commit -m "remove setting address while add a vendor"
   git add gnuncash/gnome/dialog-customer.c gnucash/import-export/customer-import/dialog-customer-import.c
   git commit -m "remove setting address while add or import a new customer"
   git push -f my-github-repo maint
```
making the obvious substitution on the last line.

2021-06-11 23:25 UTC, TianXing-Yi commented
> I didn't tell you to comment out anything. I told you to *remove* code *instead* of commenting it out. Perhaps that's what you did but didn't get the English quite right.

Thanks for your advice, now I know how to do 😄😄

2021-06-12 01:47 UTC, closed without merging